// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package comment

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	PostID    pgtype.UUID        `json:"post_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Title     pgtype.Text        `json:"title"`
	Content   pgtype.Text        `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
