// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package comment

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        uuid.UUID
	PostID    pgtype.UUID
	AuthorID  pgtype.UUID
	Title     pgtype.Text
	Content   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID       uuid.UUID
	Name     string
	Password string
}
