// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package post

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID       pgtype.UUID        `json:"id"`
	AuthorID pgtype.UUID        `json:"author_id"`
	Title    pgtype.Text        `json:"title"`
	Content  pgtype.Text        `json:"content"`
	CreateAt pgtype.Timestamptz `json:"create_at"`
}
