// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package post

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (Post, error)
	Delete(ctx context.Context, id pgtype.UUID) error
	FindAll(ctx context.Context) ([]Post, error)
	FindByID(ctx context.Context, id pgtype.UUID) (Post, error)
	Update(ctx context.Context, arg UpdateParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
