services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
      - tempo
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - observe-net
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: http://loki:3100
          - name: Tempo
            type: tempo
            url: http://tempo:3200
        EOF
        /run.sh

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - observe-net

  tempo:
    image: grafana/tempo:latest
    command: ["--config.file=/etc/tempo.yaml"]
    ports:
      - "4317:4317"     # gRPC for OTLP
      - "4318:4318"     # OTLP HTTP receiver
      - "3200:3200"     # Tempo internal HTTP server (for Grafana)
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    networks:
      - observe-net

networks:
  observe-net: