name: Build cli and backend in pull request

on:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Lint backend
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./backend
          version: v1.64

      - name: Lint CLI
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./cli
          version: v1.64

  Build-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build backend
        working-directory: ./backend
        run: |
          go mod download
          go build -v ./...

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag myusername/backend:${{ github.sha }} \
            --file Dockerfile \
            .

  Build-CLI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build CLI
        working-directory: ./cli
        run: |
          go mod download
          go build -v -o cli_forum ./...