name: Build cli and backend in pull request

on:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Lint backend
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./backend
          version: v1.64

      - name: Lint CLI
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./cli
          version: v1.64

  Test-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.25.0'

      - name: Test backend
        working-directory: ./backend
        run: make test

      - name: Test cli
        working-directory: ./backend
        run: make test

  Test-CLI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Test cli
        working-directory: ./backend
        run: make test

  Build-Backend:
    needs: Test-Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.25.0'

      - name: Build backend
        working-directory: ./backend
        run: |
          go mod download
          make build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag myusername/backend:${{ github.sha }} \
            --file Dockerfile \
            .
  Build-CLI:
    needs: Test-CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build CLI
        working-directory: ./cli
        run: |
          go mod download
          go build -v -o cli_forum ./...